cart:
    pattern:  /
    defaults: { _controller: MerciCartBundle:Cart:index }

cart_add:
    pattern:  /add/{id}
    defaults: { _controller: MerciCartBundle:Cart:add }
    requirements:
        id:  \d+

cart_delete:
    pattern:  /delete/{id}
    defaults: { _controller: MerciCartBundle:Cart:delete }
    requirements:
        id:  \d+

cart_update:
    pattern:  /update
    defaults: { _controller: MerciCartBundle:Cart:update }