homepage:
    pattern:  /
    defaults: { _controller: MerciCatalogBundle:Catalog:index }

product:
    pattern:  /product/{id}
    defaults: { _controller: MerciCatalogBundle:Catalog:product }

search:
    pattern:  /search
    defaults: { _controller: MerciCatalogBundle:Catalog:search }
