homepage:
    pattern:  /
    defaults: { _controller: MerciCatalogBundle:Catalog:index }

product:
    pattern:  /product/{id}
    defaults: { _controller: MerciCatalogBundle:Catalog:product }
    requirements:
        id:  \d+
