parameters:
#    merci_catalog.example.class: Merci\CatalogBundle\Example

services:
    merci.twig.catalog_extension:
        class: Merci\CatalogBundle\Twig\CatalogExtension
        tags:
            - { name: twig.extension }