login:
    pattern:  /login
    defaults: { _controller: MerciUserBundle:User:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

register:
    pattern:  /register
    defaults: { _controller: MerciUserBundle:User:register }